server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/cmfz
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.baizhi.wz.entity
  mapper-locations: classpath:com/baizhi/wz/mapper/*DaoMapper.xml
logging:
  level:
    com.baizhi.dao: debug
